#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dai_Ly_Ve_So_1.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDLVESO")]
	public partial class QLVESODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCongNo(CongNo instance);
    partial void UpdateCongNo(CongNo instance);
    partial void DeleteCongNo(CongNo instance);
    partial void InsertSoLuongDK(SoLuongDK instance);
    partial void UpdateSoLuongDK(SoLuongDK instance);
    partial void DeleteSoLuongDK(SoLuongDK instance);
    partial void InsertCongTy(CongTy instance);
    partial void UpdateCongTy(CongTy instance);
    partial void DeleteCongTy(CongTy instance);
    partial void InsertDaiLy(DaiLy instance);
    partial void UpdateDaiLy(DaiLy instance);
    partial void DeleteDaiLy(DaiLy instance);
    partial void InsertGiai(Giai instance);
    partial void UpdateGiai(Giai instance);
    partial void DeleteGiai(Giai instance);
    partial void InsertLoaiVeso(LoaiVeso instance);
    partial void UpdateLoaiVeso(LoaiVeso instance);
    partial void DeleteLoaiVeso(LoaiVeso instance);
    partial void InsertNhanVe(NhanVe instance);
    partial void UpdateNhanVe(NhanVe instance);
    partial void DeleteNhanVe(NhanVe instance);
    partial void InsertPhatHanh(PhatHanh instance);
    partial void UpdatePhatHanh(PhatHanh instance);
    partial void DeletePhatHanh(PhatHanh instance);
    partial void InsertPhieuChi(PhieuChi instance);
    partial void UpdatePhieuChi(PhieuChi instance);
    partial void DeletePhieuChi(PhieuChi instance);
    partial void InsertPhieuThu(PhieuThu instance);
    partial void UpdatePhieuThu(PhieuThu instance);
    partial void DeletePhieuThu(PhieuThu instance);
    #endregion
		
		public QLVESODataContext() : 
				base(global::Dai_Ly_Ve_So_1.Properties.Settings.Default.QLDLVESOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLVESODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLVESODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLVESODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLVESODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CongNo> CongNos
		{
			get
			{
				return this.GetTable<CongNo>();
			}
		}
		
		public System.Data.Linq.Table<SoLuongDK> SoLuongDKs
		{
			get
			{
				return this.GetTable<SoLuongDK>();
			}
		}
		
		public System.Data.Linq.Table<CongTy> CongTies
		{
			get
			{
				return this.GetTable<CongTy>();
			}
		}
		
		public System.Data.Linq.Table<DaiLy> DaiLies
		{
			get
			{
				return this.GetTable<DaiLy>();
			}
		}
		
		public System.Data.Linq.Table<Giai> Giais
		{
			get
			{
				return this.GetTable<Giai>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaSoXo> KetQuaSoXos
		{
			get
			{
				return this.GetTable<KetQuaSoXo>();
			}
		}
		
		public System.Data.Linq.Table<LoaiVeso> LoaiVesos
		{
			get
			{
				return this.GetTable<LoaiVeso>();
			}
		}
		
		public System.Data.Linq.Table<NhanVe> NhanVes
		{
			get
			{
				return this.GetTable<NhanVe>();
			}
		}
		
		public System.Data.Linq.Table<PhanPhoi> PhanPhois
		{
			get
			{
				return this.GetTable<PhanPhoi>();
			}
		}
		
		public System.Data.Linq.Table<PhatHanh> PhatHanhs
		{
			get
			{
				return this.GetTable<PhatHanh>();
			}
		}
		
		public System.Data.Linq.Table<PhatHanh_Nhanve> PhatHanh_Nhanves
		{
			get
			{
				return this.GetTable<PhatHanh_Nhanve>();
			}
		}
		
		public System.Data.Linq.Table<PhieuChi> PhieuChis
		{
			get
			{
				return this.GetTable<PhieuChi>();
			}
		}
		
		public System.Data.Linq.Table<PhieuThu> PhieuThus
		{
			get
			{
				return this.GetTable<PhieuThu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongNo")]
	public partial class CongNo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCongNo;
		
		private string _MaPhatHanh;
		
		private string _MaDaiLy;
		
		private System.Nullable<double> _TongSoTien;
		
		private System.Nullable<double> _SoTienConNo;
		
		private EntitySet<PhieuThu> _PhieuThus;
		
		private EntityRef<DaiLy> _DaiLy;
		
		private EntityRef<PhatHanh> _PhatHanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCongNoChanging(string value);
    partial void OnMaCongNoChanged();
    partial void OnMaPhatHanhChanging(string value);
    partial void OnMaPhatHanhChanged();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    partial void OnTongSoTienChanging(System.Nullable<double> value);
    partial void OnTongSoTienChanged();
    partial void OnSoTienConNoChanging(System.Nullable<double> value);
    partial void OnSoTienConNoChanged();
    #endregion
		
		public CongNo()
		{
			this._PhieuThus = new EntitySet<PhieuThu>(new Action<PhieuThu>(this.attach_PhieuThus), new Action<PhieuThu>(this.detach_PhieuThus));
			this._DaiLy = default(EntityRef<DaiLy>);
			this._PhatHanh = default(EntityRef<PhatHanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCongNo
		{
			get
			{
				return this._MaCongNo;
			}
			set
			{
				if ((this._MaCongNo != value))
				{
					this.OnMaCongNoChanging(value);
					this.SendPropertyChanging();
					this._MaCongNo = value;
					this.SendPropertyChanged("MaCongNo");
					this.OnMaCongNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhatHanh", DbType="VarChar(20)")]
		public string MaPhatHanh
		{
			get
			{
				return this._MaPhatHanh;
			}
			set
			{
				if ((this._MaPhatHanh != value))
				{
					if (this._PhatHanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._MaPhatHanh = value;
					this.SendPropertyChanged("MaPhatHanh");
					this.OnMaPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="VarChar(20)")]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DaiLy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTien", DbType="Float")]
		public System.Nullable<double> TongSoTien
		{
			get
			{
				return this._TongSoTien;
			}
			set
			{
				if ((this._TongSoTien != value))
				{
					this.OnTongSoTienChanging(value);
					this.SendPropertyChanging();
					this._TongSoTien = value;
					this.SendPropertyChanged("TongSoTien");
					this.OnTongSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienConNo", DbType="Float")]
		public System.Nullable<double> SoTienConNo
		{
			get
			{
				return this._SoTienConNo;
			}
			set
			{
				if ((this._SoTienConNo != value))
				{
					this.OnSoTienConNoChanging(value);
					this.SendPropertyChanging();
					this._SoTienConNo = value;
					this.SendPropertyChanged("SoTienConNo");
					this.OnSoTienConNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongNo_PhieuThu", Storage="_PhieuThus", ThisKey="MaCongNo", OtherKey="MaCongNo")]
		public EntitySet<PhieuThu> PhieuThus
		{
			get
			{
				return this._PhieuThus;
			}
			set
			{
				this._PhieuThus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_CongNo", Storage="_DaiLy", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DaiLy DaiLy
		{
			get
			{
				return this._DaiLy.Entity;
			}
			set
			{
				DaiLy previousValue = this._DaiLy.Entity;
				if (((previousValue != value) 
							|| (this._DaiLy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DaiLy.Entity = null;
						previousValue.CongNos.Remove(this);
					}
					this._DaiLy.Entity = value;
					if ((value != null))
					{
						value.CongNos.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(string);
					}
					this.SendPropertyChanged("DaiLy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhatHanh_CongNo", Storage="_PhatHanh", ThisKey="MaPhatHanh", OtherKey="MaPhatHanh", IsForeignKey=true)]
		public PhatHanh PhatHanh
		{
			get
			{
				return this._PhatHanh.Entity;
			}
			set
			{
				PhatHanh previousValue = this._PhatHanh.Entity;
				if (((previousValue != value) 
							|| (this._PhatHanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhatHanh.Entity = null;
						previousValue.CongNos.Remove(this);
					}
					this._PhatHanh.Entity = value;
					if ((value != null))
					{
						value.CongNos.Add(this);
						this._MaPhatHanh = value.MaPhatHanh;
					}
					else
					{
						this._MaPhatHanh = default(string);
					}
					this.SendPropertyChanged("PhatHanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuThus(PhieuThu entity)
		{
			this.SendPropertyChanging();
			entity.CongNo = this;
		}
		
		private void detach_PhieuThus(PhieuThu entity)
		{
			this.SendPropertyChanging();
			entity.CongNo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoLuongDK")]
	public partial class SoLuongDK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _MaLoaiveSo;
		
		private string _MaDaiLy;
		
		private System.Nullable<System.DateTime> _NgayDK;
		
		private System.Nullable<int> _SoLuongDK1;
		
		private EntityRef<DaiLy> _DaiLy;
		
		private EntityRef<LoaiVeso> _LoaiVeso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnMaLoaiveSoChanging(string value);
    partial void OnMaLoaiveSoChanged();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    partial void OnNgayDKChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDKChanged();
    partial void OnSoLuongDK1Changing(System.Nullable<int> value);
    partial void OnSoLuongDK1Changed();
    #endregion
		
		public SoLuongDK()
		{
			this._DaiLy = default(EntityRef<DaiLy>);
			this._LoaiVeso = default(EntityRef<LoaiVeso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiveSo", DbType="VarChar(20)")]
		public string MaLoaiveSo
		{
			get
			{
				return this._MaLoaiveSo;
			}
			set
			{
				if ((this._MaLoaiveSo != value))
				{
					if (this._LoaiVeso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiveSoChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiveSo = value;
					this.SendPropertyChanged("MaLoaiveSo");
					this.OnMaLoaiveSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="VarChar(20)")]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DaiLy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDK", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDK
		{
			get
			{
				return this._NgayDK;
			}
			set
			{
				if ((this._NgayDK != value))
				{
					this.OnNgayDKChanging(value);
					this.SendPropertyChanging();
					this._NgayDK = value;
					this.SendPropertyChanged("NgayDK");
					this.OnNgayDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SoLuongDK", Storage="_SoLuongDK1", DbType="Int")]
		public System.Nullable<int> SoLuongDK1
		{
			get
			{
				return this._SoLuongDK1;
			}
			set
			{
				if ((this._SoLuongDK1 != value))
				{
					this.OnSoLuongDK1Changing(value);
					this.SendPropertyChanging();
					this._SoLuongDK1 = value;
					this.SendPropertyChanged("SoLuongDK1");
					this.OnSoLuongDK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_SoLuongDK", Storage="_DaiLy", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DaiLy DaiLy
		{
			get
			{
				return this._DaiLy.Entity;
			}
			set
			{
				DaiLy previousValue = this._DaiLy.Entity;
				if (((previousValue != value) 
							|| (this._DaiLy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DaiLy.Entity = null;
						previousValue.SoLuongDKs.Remove(this);
					}
					this._DaiLy.Entity = value;
					if ((value != null))
					{
						value.SoLuongDKs.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(string);
					}
					this.SendPropertyChanged("DaiLy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiVeso_SoLuongDK", Storage="_LoaiVeso", ThisKey="MaLoaiveSo", OtherKey="MaLoaiVeSo", IsForeignKey=true)]
		public LoaiVeso LoaiVeso
		{
			get
			{
				return this._LoaiVeso.Entity;
			}
			set
			{
				LoaiVeso previousValue = this._LoaiVeso.Entity;
				if (((previousValue != value) 
							|| (this._LoaiVeso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiVeso.Entity = null;
						previousValue.SoLuongDKs.Remove(this);
					}
					this._LoaiVeso.Entity = value;
					if ((value != null))
					{
						value.SoLuongDKs.Add(this);
						this._MaLoaiveSo = value.MaLoaiVeSo;
					}
					else
					{
						this._MaLoaiveSo = default(string);
					}
					this.SendPropertyChanged("LoaiVeso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTy")]
	public partial class CongTy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCongTy;
		
		private string _TenCongTy;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<int> _Flag;
		
		private EntitySet<NhanVe> _NhanVes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCongTyChanging(string value);
    partial void OnMaCongTyChanged();
    partial void OnTenCongTyChanging(string value);
    partial void OnTenCongTyChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnFlagChanging(System.Nullable<int> value);
    partial void OnFlagChanged();
    #endregion
		
		public CongTy()
		{
			this._NhanVes = new EntitySet<NhanVe>(new Action<NhanVe>(this.attach_NhanVes), new Action<NhanVe>(this.detach_NhanVes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongTy", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCongTy
		{
			get
			{
				return this._MaCongTy;
			}
			set
			{
				if ((this._MaCongTy != value))
				{
					this.OnMaCongTyChanging(value);
					this.SendPropertyChanging();
					this._MaCongTy = value;
					this.SendPropertyChanged("MaCongTy");
					this.OnMaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCongTy
		{
			get
			{
				return this._TenCongTy;
			}
			set
			{
				if ((this._TenCongTy != value))
				{
					this.OnTenCongTyChanging(value);
					this.SendPropertyChanging();
					this._TenCongTy = value;
					this.SendPropertyChanged("TenCongTy");
					this.OnTenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Int")]
		public System.Nullable<int> Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTy_NhanVe", Storage="_NhanVes", ThisKey="MaCongTy", OtherKey="MaCongTy")]
		public EntitySet<NhanVe> NhanVes
		{
			get
			{
				return this._NhanVes;
			}
			set
			{
				this._NhanVes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanVes(NhanVe entity)
		{
			this.SendPropertyChanging();
			entity.CongTy = this;
		}
		
		private void detach_NhanVes(NhanVe entity)
		{
			this.SendPropertyChanging();
			entity.CongTy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DaiLy")]
	public partial class DaiLy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDaiLy;
		
		private string _TenDaiLy;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<int> _flag;
		
		private EntitySet<CongNo> _CongNos;
		
		private EntitySet<SoLuongDK> _SoLuongDKs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    partial void OnTenDaiLyChanging(string value);
    partial void OnTenDaiLyChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnflagChanging(System.Nullable<int> value);
    partial void OnflagChanged();
    #endregion
		
		public DaiLy()
		{
			this._CongNos = new EntitySet<CongNo>(new Action<CongNo>(this.attach_CongNos), new Action<CongNo>(this.detach_CongNos));
			this._SoLuongDKs = new EntitySet<SoLuongDK>(new Action<SoLuongDK>(this.attach_SoLuongDKs), new Action<SoLuongDK>(this.detach_SoLuongDKs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDaiLy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDaiLy
		{
			get
			{
				return this._TenDaiLy;
			}
			set
			{
				if ((this._TenDaiLy != value))
				{
					this.OnTenDaiLyChanging(value);
					this.SendPropertyChanging();
					this._TenDaiLy = value;
					this.SendPropertyChanged("TenDaiLy");
					this.OnTenDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="Int")]
		public System.Nullable<int> flag
		{
			get
			{
				return this._flag;
			}
			set
			{
				if ((this._flag != value))
				{
					this.OnflagChanging(value);
					this.SendPropertyChanging();
					this._flag = value;
					this.SendPropertyChanged("flag");
					this.OnflagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_CongNo", Storage="_CongNos", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<CongNo> CongNos
		{
			get
			{
				return this._CongNos;
			}
			set
			{
				this._CongNos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaiLy_SoLuongDK", Storage="_SoLuongDKs", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<SoLuongDK> SoLuongDKs
		{
			get
			{
				return this._SoLuongDKs;
			}
			set
			{
				this._SoLuongDKs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongNos(CongNo entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = this;
		}
		
		private void detach_CongNos(CongNo entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = null;
		}
		
		private void attach_SoLuongDKs(SoLuongDK entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = this;
		}
		
		private void detach_SoLuongDKs(SoLuongDK entity)
		{
			this.SendPropertyChanging();
			entity.DaiLy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Giai")]
	public partial class Giai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiai;
		
		private string _TenGiai;
		
		private System.Nullable<double> _SoTienNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaiChanging(string value);
    partial void OnMaGiaiChanged();
    partial void OnTenGiaiChanging(string value);
    partial void OnTenGiaiChanged();
    partial void OnSoTienNhanChanging(System.Nullable<double> value);
    partial void OnSoTienNhanChanged();
    #endregion
		
		public Giai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiai", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiai
		{
			get
			{
				return this._MaGiai;
			}
			set
			{
				if ((this._MaGiai != value))
				{
					this.OnMaGiaiChanging(value);
					this.SendPropertyChanging();
					this._MaGiai = value;
					this.SendPropertyChanged("MaGiai");
					this.OnMaGiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiai", DbType="NVarChar(30)")]
		public string TenGiai
		{
			get
			{
				return this._TenGiai;
			}
			set
			{
				if ((this._TenGiai != value))
				{
					this.OnTenGiaiChanging(value);
					this.SendPropertyChanging();
					this._TenGiai = value;
					this.SendPropertyChanged("TenGiai");
					this.OnTenGiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienNhan", DbType="Float")]
		public System.Nullable<double> SoTienNhan
		{
			get
			{
				return this._SoTienNhan;
			}
			set
			{
				if ((this._SoTienNhan != value))
				{
					this.OnSoTienNhanChanging(value);
					this.SendPropertyChanging();
					this._SoTienNhan = value;
					this.SendPropertyChanged("SoTienNhan");
					this.OnSoTienNhanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaSoXo")]
	public partial class KetQuaSoXo
	{
		
		private string _MaPhatHanh;
		
		private string _MaLoaiVeSo;
		
		private string _MaGiai;
		
		private string _SoTrung;
		
		public KetQuaSoXo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhatHanh", DbType="VarChar(20)")]
		public string MaPhatHanh
		{
			get
			{
				return this._MaPhatHanh;
			}
			set
			{
				if ((this._MaPhatHanh != value))
				{
					this._MaPhatHanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiVeSo", DbType="VarChar(20)")]
		public string MaLoaiVeSo
		{
			get
			{
				return this._MaLoaiVeSo;
			}
			set
			{
				if ((this._MaLoaiVeSo != value))
				{
					this._MaLoaiVeSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiai", DbType="VarChar(20)")]
		public string MaGiai
		{
			get
			{
				return this._MaGiai;
			}
			set
			{
				if ((this._MaGiai != value))
				{
					this._MaGiai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTrung", DbType="VarChar(10)")]
		public string SoTrung
		{
			get
			{
				return this._SoTrung;
			}
			set
			{
				if ((this._SoTrung != value))
				{
					this._SoTrung = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiVeso")]
	public partial class LoaiVeso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiVeSo;
		
		private string _Tinh;
		
		private System.Nullable<double> _GiaVe;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private System.Nullable<int> _falg;
		
		private EntitySet<SoLuongDK> _SoLuongDKs;
		
		private EntitySet<NhanVe> _NhanVes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiVeSoChanging(string value);
    partial void OnMaLoaiVeSoChanged();
    partial void OnTinhChanging(string value);
    partial void OnTinhChanged();
    partial void OnGiaVeChanging(System.Nullable<double> value);
    partial void OnGiaVeChanged();
    partial void OnNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChanged();
    partial void OnfalgChanging(System.Nullable<int> value);
    partial void OnfalgChanged();
    #endregion
		
		public LoaiVeso()
		{
			this._SoLuongDKs = new EntitySet<SoLuongDK>(new Action<SoLuongDK>(this.attach_SoLuongDKs), new Action<SoLuongDK>(this.detach_SoLuongDKs));
			this._NhanVes = new EntitySet<NhanVe>(new Action<NhanVe>(this.attach_NhanVes), new Action<NhanVe>(this.detach_NhanVes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiVeSo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiVeSo
		{
			get
			{
				return this._MaLoaiVeSo;
			}
			set
			{
				if ((this._MaLoaiVeSo != value))
				{
					this.OnMaLoaiVeSoChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiVeSo = value;
					this.SendPropertyChanged("MaLoaiVeSo");
					this.OnMaLoaiVeSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinh", DbType="NVarChar(20)")]
		public string Tinh
		{
			get
			{
				return this._Tinh;
			}
			set
			{
				if ((this._Tinh != value))
				{
					this.OnTinhChanging(value);
					this.SendPropertyChanging();
					this._Tinh = value;
					this.SendPropertyChanged("Tinh");
					this.OnTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Float")]
		public System.Nullable<double> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_falg", DbType="Int")]
		public System.Nullable<int> falg
		{
			get
			{
				return this._falg;
			}
			set
			{
				if ((this._falg != value))
				{
					this.OnfalgChanging(value);
					this.SendPropertyChanging();
					this._falg = value;
					this.SendPropertyChanged("falg");
					this.OnfalgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiVeso_SoLuongDK", Storage="_SoLuongDKs", ThisKey="MaLoaiVeSo", OtherKey="MaLoaiveSo")]
		public EntitySet<SoLuongDK> SoLuongDKs
		{
			get
			{
				return this._SoLuongDKs;
			}
			set
			{
				this._SoLuongDKs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiVeso_NhanVe", Storage="_NhanVes", ThisKey="MaLoaiVeSo", OtherKey="MaLoaiVeSo")]
		public EntitySet<NhanVe> NhanVes
		{
			get
			{
				return this._NhanVes;
			}
			set
			{
				this._NhanVes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SoLuongDKs(SoLuongDK entity)
		{
			this.SendPropertyChanging();
			entity.LoaiVeso = this;
		}
		
		private void detach_SoLuongDKs(SoLuongDK entity)
		{
			this.SendPropertyChanging();
			entity.LoaiVeso = null;
		}
		
		private void attach_NhanVes(NhanVe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiVeso = this;
		}
		
		private void detach_NhanVes(NhanVe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiVeso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVe")]
	public partial class NhanVe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVe;
		
		private string _MaCongTy;
		
		private string _MaLoaiVeSo;
		
		private System.Nullable<System.DateTime> _NgayNhanVe;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<CongTy> _CongTy;
		
		private EntityRef<LoaiVeso> _LoaiVeso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVeChanging(string value);
    partial void OnMaNhanVeChanged();
    partial void OnMaCongTyChanging(string value);
    partial void OnMaCongTyChanged();
    partial void OnMaLoaiVeSoChanging(string value);
    partial void OnMaLoaiVeSoChanged();
    partial void OnNgayNhanVeChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhanVeChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public NhanVe()
		{
			this._CongTy = default(EntityRef<CongTy>);
			this._LoaiVeso = default(EntityRef<LoaiVeso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVe", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVe
		{
			get
			{
				return this._MaNhanVe;
			}
			set
			{
				if ((this._MaNhanVe != value))
				{
					this.OnMaNhanVeChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVe = value;
					this.SendPropertyChanged("MaNhanVe");
					this.OnMaNhanVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongTy", DbType="VarChar(20)")]
		public string MaCongTy
		{
			get
			{
				return this._MaCongTy;
			}
			set
			{
				if ((this._MaCongTy != value))
				{
					if (this._CongTy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCongTyChanging(value);
					this.SendPropertyChanging();
					this._MaCongTy = value;
					this.SendPropertyChanged("MaCongTy");
					this.OnMaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiVeSo", DbType="VarChar(20)")]
		public string MaLoaiVeSo
		{
			get
			{
				return this._MaLoaiVeSo;
			}
			set
			{
				if ((this._MaLoaiVeSo != value))
				{
					if (this._LoaiVeso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiVeSoChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiVeSo = value;
					this.SendPropertyChanged("MaLoaiVeSo");
					this.OnMaLoaiVeSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhanVe", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhanVe
		{
			get
			{
				return this._NgayNhanVe;
			}
			set
			{
				if ((this._NgayNhanVe != value))
				{
					this.OnNgayNhanVeChanging(value);
					this.SendPropertyChanging();
					this._NgayNhanVe = value;
					this.SendPropertyChanged("NgayNhanVe");
					this.OnNgayNhanVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTy_NhanVe", Storage="_CongTy", ThisKey="MaCongTy", OtherKey="MaCongTy", IsForeignKey=true)]
		public CongTy CongTy
		{
			get
			{
				return this._CongTy.Entity;
			}
			set
			{
				CongTy previousValue = this._CongTy.Entity;
				if (((previousValue != value) 
							|| (this._CongTy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTy.Entity = null;
						previousValue.NhanVes.Remove(this);
					}
					this._CongTy.Entity = value;
					if ((value != null))
					{
						value.NhanVes.Add(this);
						this._MaCongTy = value.MaCongTy;
					}
					else
					{
						this._MaCongTy = default(string);
					}
					this.SendPropertyChanged("CongTy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiVeso_NhanVe", Storage="_LoaiVeso", ThisKey="MaLoaiVeSo", OtherKey="MaLoaiVeSo", IsForeignKey=true)]
		public LoaiVeso LoaiVeso
		{
			get
			{
				return this._LoaiVeso.Entity;
			}
			set
			{
				LoaiVeso previousValue = this._LoaiVeso.Entity;
				if (((previousValue != value) 
							|| (this._LoaiVeso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiVeso.Entity = null;
						previousValue.NhanVes.Remove(this);
					}
					this._LoaiVeso.Entity = value;
					if ((value != null))
					{
						value.NhanVes.Add(this);
						this._MaLoaiVeSo = value.MaLoaiVeSo;
					}
					else
					{
						this._MaLoaiVeSo = default(string);
					}
					this.SendPropertyChanged("LoaiVeso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanPhoi")]
	public partial class PhanPhoi
	{
		
		private string _MaPhatHanh;
		
		private string _MaLoaiVeSo;
		
		private string _MaDaiLy;
		
		private System.Nullable<int> _SoLuongppchoDaiLy;
		
		private System.Nullable<int> _SoLuongvetra;
		
		public PhanPhoi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhatHanh", DbType="VarChar(20)")]
		public string MaPhatHanh
		{
			get
			{
				return this._MaPhatHanh;
			}
			set
			{
				if ((this._MaPhatHanh != value))
				{
					this._MaPhatHanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiVeSo", DbType="VarChar(20)")]
		public string MaLoaiVeSo
		{
			get
			{
				return this._MaLoaiVeSo;
			}
			set
			{
				if ((this._MaLoaiVeSo != value))
				{
					this._MaLoaiVeSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="VarChar(20)")]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					this._MaDaiLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongppchoDaiLy", DbType="Int")]
		public System.Nullable<int> SoLuongppchoDaiLy
		{
			get
			{
				return this._SoLuongppchoDaiLy;
			}
			set
			{
				if ((this._SoLuongppchoDaiLy != value))
				{
					this._SoLuongppchoDaiLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongvetra", DbType="Int")]
		public System.Nullable<int> SoLuongvetra
		{
			get
			{
				return this._SoLuongvetra;
			}
			set
			{
				if ((this._SoLuongvetra != value))
				{
					this._SoLuongvetra = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhatHanh")]
	public partial class PhatHanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhatHanh;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<System.DateTime> _NgayPhatHanh;
		
		private System.Nullable<int> _SLBan;
		
		private System.Nullable<double> _DoanhThuDPH;
		
		private System.Nullable<double> _HoaHong;
		
		private System.Nullable<double> _TienThanhToan;
		
		private EntitySet<CongNo> _CongNos;
		
		private EntitySet<PhieuChi> _PhieuChis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhatHanhChanging(string value);
    partial void OnMaPhatHanhChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNgayPhatHanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayPhatHanhChanged();
    partial void OnSLBanChanging(System.Nullable<int> value);
    partial void OnSLBanChanged();
    partial void OnDoanhThuDPHChanging(System.Nullable<double> value);
    partial void OnDoanhThuDPHChanged();
    partial void OnHoaHongChanging(System.Nullable<double> value);
    partial void OnHoaHongChanged();
    partial void OnTienThanhToanChanging(System.Nullable<double> value);
    partial void OnTienThanhToanChanged();
    #endregion
		
		public PhatHanh()
		{
			this._CongNos = new EntitySet<CongNo>(new Action<CongNo>(this.attach_CongNos), new Action<CongNo>(this.detach_CongNos));
			this._PhieuChis = new EntitySet<PhieuChi>(new Action<PhieuChi>(this.attach_PhieuChis), new Action<PhieuChi>(this.detach_PhieuChis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhatHanh", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhatHanh
		{
			get
			{
				return this._MaPhatHanh;
			}
			set
			{
				if ((this._MaPhatHanh != value))
				{
					this.OnMaPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._MaPhatHanh = value;
					this.SendPropertyChanged("MaPhatHanh");
					this.OnMaPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhatHanh", DbType="Date")]
		public System.Nullable<System.DateTime> NgayPhatHanh
		{
			get
			{
				return this._NgayPhatHanh;
			}
			set
			{
				if ((this._NgayPhatHanh != value))
				{
					this.OnNgayPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._NgayPhatHanh = value;
					this.SendPropertyChanged("NgayPhatHanh");
					this.OnNgayPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBan", DbType="Int")]
		public System.Nullable<int> SLBan
		{
			get
			{
				return this._SLBan;
			}
			set
			{
				if ((this._SLBan != value))
				{
					this.OnSLBanChanging(value);
					this.SendPropertyChanging();
					this._SLBan = value;
					this.SendPropertyChanged("SLBan");
					this.OnSLBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoanhThuDPH", DbType="Float")]
		public System.Nullable<double> DoanhThuDPH
		{
			get
			{
				return this._DoanhThuDPH;
			}
			set
			{
				if ((this._DoanhThuDPH != value))
				{
					this.OnDoanhThuDPHChanging(value);
					this.SendPropertyChanging();
					this._DoanhThuDPH = value;
					this.SendPropertyChanged("DoanhThuDPH");
					this.OnDoanhThuDPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoaHong", DbType="Float")]
		public System.Nullable<double> HoaHong
		{
			get
			{
				return this._HoaHong;
			}
			set
			{
				if ((this._HoaHong != value))
				{
					this.OnHoaHongChanging(value);
					this.SendPropertyChanging();
					this._HoaHong = value;
					this.SendPropertyChanged("HoaHong");
					this.OnHoaHongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThanhToan", DbType="Float")]
		public System.Nullable<double> TienThanhToan
		{
			get
			{
				return this._TienThanhToan;
			}
			set
			{
				if ((this._TienThanhToan != value))
				{
					this.OnTienThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TienThanhToan = value;
					this.SendPropertyChanged("TienThanhToan");
					this.OnTienThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhatHanh_CongNo", Storage="_CongNos", ThisKey="MaPhatHanh", OtherKey="MaPhatHanh")]
		public EntitySet<CongNo> CongNos
		{
			get
			{
				return this._CongNos;
			}
			set
			{
				this._CongNos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhatHanh_PhieuChi", Storage="_PhieuChis", ThisKey="MaPhatHanh", OtherKey="MaPhatHanh")]
		public EntitySet<PhieuChi> PhieuChis
		{
			get
			{
				return this._PhieuChis;
			}
			set
			{
				this._PhieuChis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongNos(CongNo entity)
		{
			this.SendPropertyChanging();
			entity.PhatHanh = this;
		}
		
		private void detach_CongNos(CongNo entity)
		{
			this.SendPropertyChanging();
			entity.PhatHanh = null;
		}
		
		private void attach_PhieuChis(PhieuChi entity)
		{
			this.SendPropertyChanging();
			entity.PhatHanh = this;
		}
		
		private void detach_PhieuChis(PhieuChi entity)
		{
			this.SendPropertyChanging();
			entity.PhatHanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhatHanh_Nhanve")]
	public partial class PhatHanh_Nhanve
	{
		
		private string _MaPhatHanh;
		
		private string _MaNhanVe;
		
		public PhatHanh_Nhanve()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhatHanh", DbType="VarChar(20)")]
		public string MaPhatHanh
		{
			get
			{
				return this._MaPhatHanh;
			}
			set
			{
				if ((this._MaPhatHanh != value))
				{
					this._MaPhatHanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVe", DbType="VarChar(20)")]
		public string MaNhanVe
		{
			get
			{
				return this._MaNhanVe;
			}
			set
			{
				if ((this._MaNhanVe != value))
				{
					this._MaNhanVe = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuChi")]
	public partial class PhieuChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuChi;
		
		private string _MaPhatHanh;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private string _NoiDung;
		
		private System.Nullable<double> _SoTien;
		
		private EntityRef<PhatHanh> _PhatHanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuChiChanging(string value);
    partial void OnMaPhieuChiChanged();
    partial void OnMaPhatHanhChanging(string value);
    partial void OnMaPhatHanhChanged();
    partial void OnNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnSoTienChanging(System.Nullable<double> value);
    partial void OnSoTienChanged();
    #endregion
		
		public PhieuChi()
		{
			this._PhatHanh = default(EntityRef<PhatHanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuChi", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuChi
		{
			get
			{
				return this._MaPhieuChi;
			}
			set
			{
				if ((this._MaPhieuChi != value))
				{
					this.OnMaPhieuChiChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuChi = value;
					this.SendPropertyChanged("MaPhieuChi");
					this.OnMaPhieuChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhatHanh", DbType="VarChar(20)")]
		public string MaPhatHanh
		{
			get
			{
				return this._MaPhatHanh;
			}
			set
			{
				if ((this._MaPhatHanh != value))
				{
					if (this._PhatHanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._MaPhatHanh = value;
					this.SendPropertyChanged("MaPhatHanh");
					this.OnMaPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(200)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Float")]
		public System.Nullable<double> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhatHanh_PhieuChi", Storage="_PhatHanh", ThisKey="MaPhatHanh", OtherKey="MaPhatHanh", IsForeignKey=true)]
		public PhatHanh PhatHanh
		{
			get
			{
				return this._PhatHanh.Entity;
			}
			set
			{
				PhatHanh previousValue = this._PhatHanh.Entity;
				if (((previousValue != value) 
							|| (this._PhatHanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhatHanh.Entity = null;
						previousValue.PhieuChis.Remove(this);
					}
					this._PhatHanh.Entity = value;
					if ((value != null))
					{
						value.PhieuChis.Add(this);
						this._MaPhatHanh = value.MaPhatHanh;
					}
					else
					{
						this._MaPhatHanh = default(string);
					}
					this.SendPropertyChanged("PhatHanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuThu")]
	public partial class PhieuThu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuThu;
		
		private string _MaCongNo;
		
		private System.Nullable<System.DateTime> _NgayThu;
		
		private System.Nullable<double> _SoTienNop;
		
		private System.Nullable<int> _Flag;
		
		private EntityRef<CongNo> _CongNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuThuChanging(string value);
    partial void OnMaPhieuThuChanged();
    partial void OnMaCongNoChanging(string value);
    partial void OnMaCongNoChanged();
    partial void OnNgayThuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThuChanged();
    partial void OnSoTienNopChanging(System.Nullable<double> value);
    partial void OnSoTienNopChanged();
    partial void OnFlagChanging(System.Nullable<int> value);
    partial void OnFlagChanged();
    #endregion
		
		public PhieuThu()
		{
			this._CongNo = default(EntityRef<CongNo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuThu", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuThu
		{
			get
			{
				return this._MaPhieuThu;
			}
			set
			{
				if ((this._MaPhieuThu != value))
				{
					this.OnMaPhieuThuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuThu = value;
					this.SendPropertyChanged("MaPhieuThu");
					this.OnMaPhieuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongNo", DbType="VarChar(20)")]
		public string MaCongNo
		{
			get
			{
				return this._MaCongNo;
			}
			set
			{
				if ((this._MaCongNo != value))
				{
					if (this._CongNo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCongNoChanging(value);
					this.SendPropertyChanging();
					this._MaCongNo = value;
					this.SendPropertyChanged("MaCongNo");
					this.OnMaCongNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThu
		{
			get
			{
				return this._NgayThu;
			}
			set
			{
				if ((this._NgayThu != value))
				{
					this.OnNgayThuChanging(value);
					this.SendPropertyChanging();
					this._NgayThu = value;
					this.SendPropertyChanged("NgayThu");
					this.OnNgayThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienNop", DbType="Float")]
		public System.Nullable<double> SoTienNop
		{
			get
			{
				return this._SoTienNop;
			}
			set
			{
				if ((this._SoTienNop != value))
				{
					this.OnSoTienNopChanging(value);
					this.SendPropertyChanging();
					this._SoTienNop = value;
					this.SendPropertyChanged("SoTienNop");
					this.OnSoTienNopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Int")]
		public System.Nullable<int> Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongNo_PhieuThu", Storage="_CongNo", ThisKey="MaCongNo", OtherKey="MaCongNo", IsForeignKey=true)]
		public CongNo CongNo
		{
			get
			{
				return this._CongNo.Entity;
			}
			set
			{
				CongNo previousValue = this._CongNo.Entity;
				if (((previousValue != value) 
							|| (this._CongNo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongNo.Entity = null;
						previousValue.PhieuThus.Remove(this);
					}
					this._CongNo.Entity = value;
					if ((value != null))
					{
						value.PhieuThus.Add(this);
						this._MaCongNo = value.MaCongNo;
					}
					else
					{
						this._MaCongNo = default(string);
					}
					this.SendPropertyChanged("CongNo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
